### ISSUE TITLE
additional maintainer(s)?

### ISSUE THREAD

**Issue by aly-fly** [aly-fly/EleksTubeHAX#108]
@SmittyHalibut are you still around? :) 
Can you please promote the @Martinius79 to a co-developer of this project, so that I don't need to check and validate every pull request - there are many of them 💯

**Comment by SmittyHalibut** [comment]
Invite sent.  Thanks for the heads up, you're right that I'm not paying much attention to activity here.  I do pay attention to mentions, however.

I'm still willing to just transfer ownership to you, @aly-fly.  You've done way more to support this project than I ever did.  Let me know if you want to make that happen.

Leaving this issue open until you decide.

**Comment by aly-fly** [comment]
> I'm still willing to just transfer ownership to you, @aly-fly. 

I am in. Ok let's do this.

**Comment by SmittyHalibut** [comment]
![image](https://github.com/user-attachments/assets/2a06df04-bd4a-417a-a98e-c81e612d0ca0)

SO CLOSE!  :-)

Make sure your local repo is merged into mine, then delete yours.  Tell me when that's done, and I'll attempt the transfer again.

**Comment by aly-fly** [comment]
I renamed it. My repo is an original fork, already stale for some time. Will delete it after a short review.

**Comment by SmittyHalibut** [comment]
![image](https://github.com/user-attachments/assets/cccc16bb-d2a7-4842-a95f-1972c53ef36b)

Bugger.  I think it needs you to delete it first.  It probably doesn't like that its a fork.

**Comment by aly-fly** [comment]
Done. Went to electronic heaven.

**Comment by SmittyHalibut** [comment]
![image](https://github.com/user-attachments/assets/6f1ee9e8-4db3-4163-b2cb-ce4d9be43bab)

Yay!

**Comment by aly-fly** [comment]
It looks like that transfer was successful! Thank you.

**Comment by Martinius79** [comment]
Hello again!

Happy to see that you were "promoted" aly-fly :)

I guess, because the ownership changed, the invitation from SmittyHalibut is not valid anymore.

![image](https://github.com/user-attachments/assets/cab9631f-6211-48d6-86f7-ba57bf2c046a)

Maybe you can invite me again?
